apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  # namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-image: mustyfdn/vaultagent:v1
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/template-static-secret-render-interval: "2m"
        vault.hashicorp.com/agent-inject-command-env.json: "sh /opt/restart_deployment.sh"

        vault.hashicorp.com/agent-inject-secret-env.json: "mustyfdn/data/secret"
        vault.hashicorp.com/agent-inject-template-env.json: |
          {{- with secret "mustyfdn/data/secret" -}}
            {{ .Data | toUnescapedJSON }}
          {{- end }}


        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "secret-role"
      labels:
        app: nginx
    spec:
      serviceAccountName: vault-rollout-sa
      shareProcessNamespace: true
      containers:
      - image: nginx
        name: nginx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-rollout-sa
  # namespace: vault
