---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rollouts-role
  # namespace: vault
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - delete
      - watch
  - apiGroups: ["apps","extensions"]
    resources:
      - deployments
      - deployments/scale
      - deployments/status
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - patch
      - update
      - watch
      - scale
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rollouts-role-binding
  # namespace: vault
subjects:
- kind: ServiceAccount
  name: vault-rollout-sa #admin-api-gateway
  # namespace: vault
# - kind: ServiceAccount
#   name: account-service
#   namespace: vault
roleRef:
  kind: Role
  name: rollouts-role
  apiGroup: rbac.authorization.k8s.io
